name: gambatte libretro Windows x86_64

on:
  workflow_dispatch:

jobs:
  Windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          wget
          git
          make
          mingw-w64-x86_64-binutils
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-zlib
          mingw-w64-x86_64-pkg-config
          zip
    - name: Checkout source
      run: git clone https://github.com/schmurtzm/gambatte-libretro.git && cd gambatte-libretro
    - shell: msys2 {0}
      working-directory: gambatte-libretro
      run: |
        make -j8
        zip -9 ../gambatte_libretro.dll.zip gambatte_libretro.dll
    - name: Upload the build artifacts
      uses: actions/upload-artifact@v3.0.0
      with:
        name: gambatte_libretro
        path: gambatte-libretro/*
        if-no-files-found: error
        retention-days: 90

